[package]
name = "ggg"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
num_cpus = "1.16"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
wgpu = "23.0"
winit = "0.30"
